In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import time
from tqdm import tqdm
import os, sys
import json
import ast

In [4]:
path = "C:/Users/derwi/OneDrive/Documentos/japon/" #Usar ruta de tu equipo.

In [5]:
with open(path+'sb_events.json', 'r', encoding="utf8") as file:
    events = json.load(file)

In [6]:
table_events = pd.json_normalize(events)

In [7]:
# Ahora observemos algo importante que hace parte de la carga y transformación de los datos para ser almacenados. 
# Miremos que las ubicaciones de los eventos están almacenados en listas del tipo [x,y]:
table_events['location']

0                  None
1                  None
2                  None
3                  None
4              [60, 40]
               ...
1244336    [80.3, 22.6]
1244337    [40.7, 55.5]
1244338    [74.1, 25.2]
1244339            None
1244340            None
Name: location, Length: 1244341, dtype: object

In [8]:
#Por tanto, debemos obtener las columnas separadas para X y para Y 
# La mejor forma es obtenerlo desde el json file, yendo fila por fila verificando si 
# existe una lista de coordenadas en cada celda del location para extraer el primer valor (x) o e segundo valor (y)

In [9]:
x = []
y = []
pass_endx = []
pass_endy = []
carry_endx = []
carry_endy = []
shot_endx = []
shot_endy = []

#Profe agregue 'shot.end_location'

for i in range(len(table_events)):
    
    ## Location
    if events[i]['location']==None:
        x.append(np.nan)
        y.append(np.nan)
    else:
        x.append(events[i]['location'][0])
        y.append(events[i]['location'][1])
        
    ## Pass end location
    if events[i]['pass.end_location']==None:
        pass_endx.append(np.nan)
        pass_endy.append(np.nan)
    else:
        pass_endx.append(events[i]['pass.end_location'][0])
        pass_endy.append(events[i]['pass.end_location'][1])
    
    ## Carry end location
    if events[i]['carry.end_location']==None:
        carry_endx.append(np.nan)
        carry_endy.append(np.nan)
    else:
        carry_endx.append(events[i]['carry.end_location'][0])
        carry_endy.append(events[i]['carry.end_location'][1])

    ## shot.end_location    
    if events[i]['shot.end_location']==None:
        shot_endx.append(np.nan)
        shot_endy.append(np.nan)
    else:
        shot_endx.append(events[i]['shot.end_location'][0])
        shot_endy.append(events[i]['shot.end_location'][1])

table_events['x'] = x
table_events['y'] = y
table_events['pass_endx'] = pass_endx
table_events['pass_endy'] = pass_endy
table_events['carry_endx'] = carry_endx
table_events['carry_endy'] = carry_endy
table_events['shot_endx'] = shot_endx
table_events['shot_endy'] = shot_endy
table_events

,id,index,period,timestamp,minute,second,possession,duration,related_events,location,...,goalkeeper.success_out,goalkeeper.success_in_play,x,y,pass_endx,pass_endy,carry_endx,carry_endy,shot_endx,shot_endy
0,dc1f3c18-004f-45d9-8f86-71d670f9cd97,1,1,00:00:00.000,0,0,1,0.0000,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8e81e4fd-fc8c-4efb-b9c4-6d2a55008d43,2,1,00:00:00.000,0,0,1,0.0000,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,35110677-aaec-4db6-982d-63ae9e8f5f78,3,1,00:00:00.000,0,0,1,0.0000,133fd42b-056e-4634-9b32-86838cab760e,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,133fd42b-056e-4634-9b32-86838cab760e,4,1,00:00:00.000,0,0,1,0.0000,35110677-aaec-4db6-982d-63ae9e8f5f78,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20a0dc1c-0dde-41ac-b07b-ed0265e6a540,5,1,00:00:00.657,0,0,2,1.2832,4ff7ee07-01fb-44c0-b669-63b31f1145ba,"[60, 40]",...,NaN,NaN,60.0,40.0,39.5,32.6,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1244336,9b224577-90e6-4807-991f-7739b7c77cc6,3691,2,00:52:37.392,97,37,199,2.4848,"[5e391a76-64ad-4a27-8cb7-0aac899c0b0d, ee8e31b...","[80.3, 22.6]",...,NaN,NaN,80.3,22.6,NaN,NaN,74.1,25.2,NaN,NaN
1244337,5e391a76-64ad-4a27-8cb7-0aac899c0b0d,3692,2,00:52:38.733,97,38,199,1.1447,"[ee8e31bd-8d6a-490e-8c40-819357245b68, 9b22457...","[40.7, 55.5]",...,NaN,NaN,40.7,55.5,NaN,NaN,NaN,NaN,NaN,NaN
1244338,ee8e31bd-8d6a-490e-8c40-819357245b68,3693,2,00:52:39.877,97,39,199,0.9747,5e391a76-64ad-4a27-8cb7-0aac899c0b0d,"[74.1, 25.2]",...,NaN,NaN,74.1,25.2,71.9,14.1,NaN,NaN,NaN,NaN
1244339,bbeb8172-4b3d-4efc-899c-6d201d85659b,3694,2,00:52:40.180,97,40,199,0.0000,856e1c3e-0215-4e22-bb76-4786030fb72d,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1244340,856e1c3e-0215-4e22-bb76-4786030fb72d,3695,2,00:52:40.180,97,40,199,0.0000,bbeb8172-4b3d-4efc-899c-6d201d85659b,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Guardar la base de datos en un parquet, 
# Es un formato de almacenamiento muy eficiente en términos de almacenamiento pero también en términos de carga de datos:

In [11]:
table_events.to_parquet(path+'table_events_J1_2024.parquet.gzip',engine='pyarrow',compression='gzip',index=False)

ArrowTypeError: ("Expected bytes, got a 'list' object", 'Conversion failed for column related_events with type object')

In [ ]:
# El error que aparece aquí es porque ciertas columnas tienen listas dentro de sus celdas, 
# en este caso la columna "related_events". Normalmente, deberíamos buscar la forma de extrar 
# la información requerida de esa columna y luego borrarla. En esta asesoría no vamos a utilizar dicha columna, 
# pero no quiero borrarla entonces la voy a convertir en string para poder grabar los datos:

In [ ]:
table_events['related_events'] = table_events['related_events'].astype(str)

In [ ]:
# Listo, ya con los datos grabados, solo quiero probar la carga de los datos, 
# para de aquí en adelante trabajar con ese archivo parquet. 
# Primero voy a borrar los datos actuales "tabla_events" y luego voy a cargar los datos que guardamos en parquet:

In [ ]:
del table_events

In [ ]:
%%time
table_events = pd.read_parquet(path+'table_events_J1_2024.parquet.gzip')